# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc ""
  homepage "https://flowexec.io"
  version "1.0.0"
  license "Apache-2.0"

  depends_on "xclip" if OS.linux?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flowexec/flow/releases/download/v1.0.0/flow_v1.0.0_darwin_amd64.tar.gz"
      sha256 "26f4da360bfc63f1109d11884a69b1aff5bd8f862c6afb7ef36abf579efac66e"

      def install
        bin.install "flow"
        bash_completion.install "completions/flow.bash"
        zsh_completion.install "completions/flow.zsh"
        fish_completion.install "completions/flow.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flowexec/flow/releases/download/v1.0.0/flow_v1.0.0_darwin_arm64.tar.gz"
      sha256 "c1b0f8e0fb90714d9a56db520c0450b4f68eaf5142fd51c575066a1cd257de5c"

      def install
        bin.install "flow"
        bash_completion.install "completions/flow.bash"
        zsh_completion.install "completions/flow.zsh"
        fish_completion.install "completions/flow.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/flowexec/flow/releases/download/v1.0.0/flow_v1.0.0_linux_amd64.tar.gz"
      sha256 "5ff5c22fe7b6d648c059b5a1c7d91b45ffd0a5b0e0a73b1647e32ca5fd7a36f2"
      def install
        bin.install "flow"
        bash_completion.install "completions/flow.bash"
        zsh_completion.install "completions/flow.zsh"
        fish_completion.install "completions/flow.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/flowexec/flow/releases/download/v1.0.0/flow_v1.0.0_linux_arm64.tar.gz"
      sha256 "6342dee9e3c753b1b8ef6cf7c58917a4bf29f857f195e962995f2f43632a8720"
      def install
        bin.install "flow"
        bash_completion.install "completions/flow.bash"
        zsh_completion.install "completions/flow.zsh"
        fish_completion.install "completions/flow.fish"
      end
    end
  end

  test do
    system "#{bin}/flow --version"
  end
end
