# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc ""
  homepage "https://flowexec.io"
  version "1.0.0-beta1"
  license "Apache-2.0"

  depends_on "xclip" if OS.linux?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jahvon/flow/releases/download/v1.0.0-beta1/flow_v1.0.0-beta1_darwin_amd64.tar.gz"
      sha256 "00f2ffff8f103d471229728831ae3fce1ad3b819974ef0e57b19de112a89a90f"

      def install
        bin.install "flow"
        bash_completion.install "completions/flow.bash"
        zsh_completion.install "completions/flow.zsh"
        fish_completion.install "completions/flow.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jahvon/flow/releases/download/v1.0.0-beta1/flow_v1.0.0-beta1_darwin_arm64.tar.gz"
      sha256 "6dbbbb9e893f79bfb1a9535b8b8cba32df84ac7c280a3f32b2a69fbd85614996"

      def install
        bin.install "flow"
        bash_completion.install "completions/flow.bash"
        zsh_completion.install "completions/flow.zsh"
        fish_completion.install "completions/flow.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jahvon/flow/releases/download/v1.0.0-beta1/flow_v1.0.0-beta1_linux_amd64.tar.gz"
      sha256 "475d0eeae1952568821a67e52e8dc327eafaa1beb611057ead582c351ab128e1"
      def install
        bin.install "flow"
        bash_completion.install "completions/flow.bash"
        zsh_completion.install "completions/flow.zsh"
        fish_completion.install "completions/flow.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jahvon/flow/releases/download/v1.0.0-beta1/flow_v1.0.0-beta1_linux_arm64.tar.gz"
      sha256 "ca112a1307eb08cd00527e641bca52b3d676bd5225e8c08b21238ea85282c875"
      def install
        bin.install "flow"
        bash_completion.install "completions/flow.bash"
        zsh_completion.install "completions/flow.zsh"
        fish_completion.install "completions/flow.fish"
      end
    end
  end

  test do
    system "#{bin}/flow --version"
  end
end
