# This file was generated by GoReleaser. DO NOT EDIT.
cask "flow" do
  desc ""
  homepage "https://flowexec.io"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flow"
  bash_completion "scripts/completions/flow.bash"
  zsh_completion "scripts/completions/flow.zsh"
  fish_completion "scripts/completions/flow.fish"

  on_macos do
    on_intel do
      url "https://github.com/flowexec/flow/releases/download/v1.1.0/flow_v1.1.0_darwin_amd64.tar.gz"
      sha256 "78bf196e2d709161e3d79d17918970278103fdf3924a098595cb01cab6d84736"
    end
    on_arm do
      url "https://github.com/flowexec/flow/releases/download/v1.1.0/flow_v1.1.0_darwin_arm64.tar.gz"
      sha256 "22f164c517d6cdaf832b68a265d2b911ffc624e71526f6a2167fcc5aec579487"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/flowexec/flow/releases/download/v1.1.0/flow_v1.1.0_linux_amd64.tar.gz"
      sha256 "ce57311e035e89c300fa9594670b6534de656a75e881109756401c71ecff0fe5"
    end
    on_arm do
      url "https://github.com/flowexec/flow/releases/download/v1.1.0/flow_v1.1.0_linux_arm64.tar.gz"
      sha256 "62e625f5937fc54fce5a44200cc119fda54d2c9d825fe84633044cf0c99e2716"
    end
  end

  conflicts_with formula: [
      "flow",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flow"]
    end
  end

  # No zap stanza required
end
