# This file was generated by GoReleaser. DO NOT EDIT.
cask "flow" do
  name "flow"
  desc ""
  homepage "https://flowexec.io"
  version "2.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flow"
  bash_completion "scripts/completions/flow.bash"
  zsh_completion "scripts/completions/flow.zsh"
  fish_completion "scripts/completions/flow.fish"

  on_macos do
    on_intel do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_darwin_amd64.tar.gz"
      sha256 "3be7435c88af43ad2fb91c8b4ac42441520c4d11ecace3832fcfad31b4054b98"
    end
    on_arm do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_darwin_arm64.tar.gz"
      sha256 "86319c4d4df3a7845b26181fcbbe1a3565a33e07d4a2f03ff32bc8125471fe52"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_linux_amd64.tar.gz"
      sha256 "a5617142fa808e18d09bcd3c44ad7d3b3677569e726448438aada6cea7a5caa1"
    end
    on_arm do
      url "https://github.com/flowexec/flow/releases/download/v#{version}/flow_v#{version}_linux_arm64.tar.gz"
      sha256 "6cd5eadfac8869e601723fa23652fa73b2c250dac7d982d6adbd5d45a49dbb9a"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flow"]
    end
  end

  # No zap stanza required
end
