# This file was generated by GoReleaser. DO NOT EDIT.
cask "flow" do
  desc ""
  homepage "https://flowexec.io"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flow"
  bash_completion "completions/flow.bash"
  zsh_completion "completions/flow.zsh"
  fish_completion "completions/flow.fish"

  on_macos do
    on_intel do
      url "https://github.com/flowexec/flow/releases/download/v1.0.2/flow_v1.0.2_darwin_amd64.tar.gz"
      sha256 "515bafb85a680206cc448d3e9658e103de3fa99bb378699e96055131066146ca"
    end
    on_arm do
      url "https://github.com/flowexec/flow/releases/download/v1.0.2/flow_v1.0.2_darwin_arm64.tar.gz"
      sha256 "d77378cacd69d155e7e95c2815930f99eead995c1ccd08008e3d1173dfe378ec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/flowexec/flow/releases/download/v1.0.2/flow_v1.0.2_linux_amd64.tar.gz"
      sha256 "7ed3dfb1b240bfbf2f3f4f32c4415b0987e98218bcc35561952ace596278638e"
    end
    on_arm do
      url "https://github.com/flowexec/flow/releases/download/v1.0.2/flow_v1.0.2_linux_arm64.tar.gz"
      sha256 "3e71cdfbbe6f55fdc34edd3f2a841abeca0a24f0f39a5a715253b0fbcb10e349"
    end
  end

  conflicts_with formula: [
      "flow",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flow"]
    end
  end

  # No zap stanza required
end
