# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc ""
  homepage "https://flowexec.io"
  version "0.6.0"
  license "Apache-2.0"

  depends_on "xclip" if OS.linux?

  on_macos do
    on_intel do
      url "https://github.com/jahvon/flow/releases/download/v0.6.0/flow_v0.6.0_darwin_amd64.tar.gz"
      sha256 "a7f53b3453d838e7c29c56ed0b5962436f9fe182ef4204d50be3ef631f787b21"

      def install
        bin.install "flow"
        bash_completion.install "completions/flow.bash"
        zsh_completion.install "completions/flow.zsh"
        fish_completion.install "completions/flow.fish"
      end
    end
    on_arm do
      url "https://github.com/jahvon/flow/releases/download/v0.6.0/flow_v0.6.0_darwin_arm64.tar.gz"
      sha256 "5e22477d13e3564c51f054ef198bf0ed1840ce5814fcb9b03c9e1bef70fed0c4"

      def install
        bin.install "flow"
        bash_completion.install "completions/flow.bash"
        zsh_completion.install "completions/flow.zsh"
        fish_completion.install "completions/flow.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jahvon/flow/releases/download/v0.6.0/flow_v0.6.0_linux_amd64.tar.gz"
        sha256 "a4197838353ede4726fe0a0ce48de67d7773d03b1985547fb1952279f248a658"

        def install
          bin.install "flow"
          bash_completion.install "completions/flow.bash"
          zsh_completion.install "completions/flow.zsh"
          fish_completion.install "completions/flow.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jahvon/flow/releases/download/v0.6.0/flow_v0.6.0_linux_arm64.tar.gz"
        sha256 "c38add3337e3de0034a5c7b084e8f3bdfc9410d144758e41fde4039748d2bec5"

        def install
          bin.install "flow"
          bash_completion.install "completions/flow.bash"
          zsh_completion.install "completions/flow.zsh"
          fish_completion.install "completions/flow.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/flow --version"
  end
end
