# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc ""
  homepage "https://flowexec.io"
  version "0.5.2"
  license "Apache-2.0"

  depends_on "xclip"

  on_macos do
    on_intel do
      url "https://github.com/jahvon/flow/releases/download/v0.5.2/flow_v0.5.2_darwin_amd64.tar.gz"
      sha256 "fd55fab5177d766a284f23484c708cc3c1cbe51b655d65632ae52d9047becd0c"

      def install
        bin.install "flow"
        bash_completion.install "completions/flow.bash"
        zsh_completion.install "completions/flow.zsh"
        fish_completion.install "completions/flow.fish"
      end
    end
    on_arm do
      url "https://github.com/jahvon/flow/releases/download/v0.5.2/flow_v0.5.2_darwin_arm64.tar.gz"
      sha256 "a35d5eaea9a20a15cb0e5d64b6dc8fa1a7fafe5feea0690cbe0321ad5b2b4ed6"

      def install
        bin.install "flow"
        bash_completion.install "completions/flow.bash"
        zsh_completion.install "completions/flow.zsh"
        fish_completion.install "completions/flow.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jahvon/flow/releases/download/v0.5.2/flow_v0.5.2_linux_amd64.tar.gz"
        sha256 "d0e925ddd24ea70234360b13c05bf83a0200c7cf86cd28e1508727b01ee57591"

        def install
          bin.install "flow"
          bash_completion.install "completions/flow.bash"
          zsh_completion.install "completions/flow.zsh"
          fish_completion.install "completions/flow.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jahvon/flow/releases/download/v0.5.2/flow_v0.5.2_linux_arm64.tar.gz"
        sha256 "58224d962b5e77ae7233d9ab61b72c99d54f91a1c92b1bb82b66517e9e6038ae"

        def install
          bin.install "flow"
          bash_completion.install "completions/flow.bash"
          zsh_completion.install "completions/flow.zsh"
          fish_completion.install "completions/flow.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/flow --version"
  end
end
