# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc ""
  homepage "https://flowexec.io"
  version "0.6.2"
  license "Apache-2.0"

  depends_on "xclip" if OS.linux?

  on_macos do
    on_intel do
      url "https://github.com/jahvon/flow/releases/download/v0.6.2/flow_v0.6.2_darwin_amd64.tar.gz"
      sha256 "d6e1718686d8008cf0f9816ebca7f439a2c90be9afbd7dec5354cbe2c9782f80"

      def install
        bin.install "flow"
        bash_completion.install "completions/flow.bash"
        zsh_completion.install "completions/flow.zsh"
        fish_completion.install "completions/flow.fish"
      end
    end
    on_arm do
      url "https://github.com/jahvon/flow/releases/download/v0.6.2/flow_v0.6.2_darwin_arm64.tar.gz"
      sha256 "146b5cee736e410fa0bda589dabd4d11ac9345528250e32a2295562ec4b55c0d"

      def install
        bin.install "flow"
        bash_completion.install "completions/flow.bash"
        zsh_completion.install "completions/flow.zsh"
        fish_completion.install "completions/flow.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jahvon/flow/releases/download/v0.6.2/flow_v0.6.2_linux_amd64.tar.gz"
        sha256 "590156d2ab6261d9ab81b2ded0f1a088503a2ec408f7a2e759f9378fd2bcece5"

        def install
          bin.install "flow"
          bash_completion.install "completions/flow.bash"
          zsh_completion.install "completions/flow.zsh"
          fish_completion.install "completions/flow.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jahvon/flow/releases/download/v0.6.2/flow_v0.6.2_linux_arm64.tar.gz"
        sha256 "be08912d7d0f2f0b1c218982ce0b4097c3abe970972eeee1cf1e41a6791c14e7"

        def install
          bin.install "flow"
          bash_completion.install "completions/flow.bash"
          zsh_completion.install "completions/flow.zsh"
          fish_completion.install "completions/flow.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/flow --version"
  end
end
